FROM php:8.4-fpm-alpine

# Instalar dependências
RUN apk add --no-cache \
    bash \
    git \
    curl \
    unzip \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    libxml2-dev \
    oniguruma-dev \
    zip \
    icu-dev \
    mysql-client \
    supervisor \
    tzdata

# Instalar extensões PHP
RUN docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
        --with-webp \
 && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        mbstring \
        exif \
        pcntl \
        bcmath \
        intl \
        gd \
        opcache

# Timezone
ENV TZ=America/Sao_Paulo

# Diretório de trabalho
WORKDIR /var/www/html

# Copiar código do projeto
COPY . .

# Instalar o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# Copiar supervisor config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Comando de inicialização
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
